### ISSUE TITLE
[BUG🐛] Output quality worse when using finetuned model in auralis than in coqui

### ISSUE THREAD

**Issue by C00reNUT** [astramind-ai/Auralis#27] opened 2024-12-05 10:59 UTC
Hello,

When I export and run finetuned model from coqui using auralis, using the same reference audio and temperature, I get very different output quality - the voice doesn't sound similar to the reference voice and the quality of the language pronunciation is also much worse.

Are there some default settings that match the coqui model? I have played with few of the sampling settings but the quality is still much inferior... Or did you made changes in the model architecture a bit?

Thank you!

**Comment by elvinzade** [comment] 2024-12-05 11:22
Hello @C00reNUT, for inference file which config.json file you used. When i use the config.json file provided in the AstraMindAI/xttsv2 model it give the missing keys and unexpected keys errors(model weigths). For config.json file used when i finetune the model it does not work with the their code implementation. 
Thank you.

**Comment by mlinmg** [comment] 2024-12-05 12:49
@C00reNUT the model is numerically identical to the reference implementation with temperature = 0, are you saving the files? some users have found out that our bitrate is different from the coqui's one(the settings for the bitrate are in the TTSOutput object)
To see if the problem is in the audio saving you can try to output.play() the audios form both without saving to see if there are differences.

**Comment by mlinmg** [comment] 2024-12-06 13:29
@C00reNUT yes we do preprocessing by default (which is wrong), it'll be removed in the next release. Please for now try it out with TTSRequest(..., enhance_speech=False)

**Comment by mlinmg** [comment] 2024-12-09 09:19
Is you r finetune public? if so i'll try with that to see the problem

**Comment by mlinmg** [comment] 2024-12-14 14:10
@C00reNUT THere was an error in the converison script, it should be fixed now! please let me knowe if the issue had been resolved!

**Closed as completed** 2024-12-19 11:45 UTC
Labels: bug
